cd ~/Desktop
mkdir FullCircleMagazine
cd FullCircleMagazine


wget http://dl.fullcirclemagazine.org/issue39_en.pdf
wget http://dl.fullcirclemagazine.org/issue38_en.pdf
wget http://dl.fullcirclemagazine.org/issue37_en.pdf
wget http://dl.fullcirclemagazine.org/issue36_en.pdf
wget http://dl.fullcirclemagazine.org/issue35_en.pdf
wget http://dl.fullcirclemagazine.org/issue34_en.pdf
wget http://dl.fullcirclemagazine.org/issue33_en.pdf
wget http://dl.fullcirclemagazine.org/issue32_en.pdf
wget http://dl.fullcirclemagazine.org/issue31_en.pdf
wget http://dl.fullcirclemagazine.org/issue30_en.pdf
wget http://dl.fullcirclemagazine.org/issue29_en.pdf
wget http://dl.fullcirclemagazine.org/issue28_en.pdf
wget http://dl.fullcirclemagazine.org/issue27_en.pdf
wget http://dl.fullcirclemagazine.org/issue26_en.pdf
wget http://dl.fullcirclemagazine.org/issue25_en.pdf
wget http://dl.fullcirclemagazine.org/issue24_en.pdf
wget http://dl.fullcirclemagazine.org/issue23_en.pdf
wget http://dl.fullcirclemagazine.org/issue22_en.pdf
wget http://dl.fullcirclemagazine.org/issue21_en.pdf
wget http://dl.fullcirclemagazine.org/issue20_en.pdf
wget http://dl.fullcirclemagazine.org/issue19_en.pdf
wget http://dl.fullcirclemagazine.org/issue18_en.pdf
wget http://dl.fullcirclemagazine.org/issue17_en.pdf
wget http://dl.fullcirclemagazine.org/issue16_en.pdf
wget http://dl.fullcirclemagazine.org/issue15_en.pdf
wget http://dl.fullcirclemagazine.org/issue14_en.pdf
wget http://dl.fullcirclemagazine.org/issue13_en.pdf
wget http://dl.fullcirclemagazine.org/issue12_en.pdf
wget http://dl.fullcirclemagazine.org/issue11_en.pdf
wget http://dl.fullcirclemagazine.org/issue10_en.pdf
wget http://dl.fullcirclemagazine.org/issue9_en.pdf
wget http://dl.fullcirclemagazine.org/issue8_en.pdf
wget http://dl.fullcirclemagazine.org/issue7_en.pdf
wget http://dl.fullcirclemagazine.org/issue6_en.pdf
wget http://dl.fullcirclemagazine.org/issue5_en.pdf
wget http://dl.fullcirclemagazine.org/issue4_en.pdf
wget http://dl.fullcirclemagazine.org/issue3_en.pdf
wget http://dl.fullcirclemagazine.org/issue2_en.pdf
wget http://dl.fullcirclemagazine.org/issue1_en.pdf
