cd ~/Desktop
mkdir FullCircleMagazine
cd FullCircleMagazine


wget http://dl.fullcirclemagazine.org/issue122_en.pdf
wget http://dl.fullcirclemagazine.org/issue121_en.pdf
wget http://dl.fullcirclemagazine.org/issue120_en.pdf
wget http://dl.fullcirclemagazine.org/issue119_en.pdf
wget http://dl.fullcirclemagazine.org/issue118_en.pdf
wget http://dl.fullcirclemagazine.org/issue117_en.pdf
wget http://dl.fullcirclemagazine.org/issue116_en.pdf
wget http://dl.fullcirclemagazine.org/issue115_en.pdf
wget http://dl.fullcirclemagazine.org/issue114_en.pdf
wget http://dl.fullcirclemagazine.org/issue113_en.pdf
wget http://dl.fullcirclemagazine.org/issue112_en.pdf
wget http://dl.fullcirclemagazine.org/issue111_en.pdf
wget http://dl.fullcirclemagazine.org/issue110_en.pdf
wget http://dl.fullcirclemagazine.org/issue109_en.pdf
wget http://dl.fullcirclemagazine.org/issue108_en.pdf
wget http://dl.fullcirclemagazine.org/issue107_en.pdf
wget http://dl.fullcirclemagazine.org/issue106_en.pdf
wget http://dl.fullcirclemagazine.org/issue105_en.pdf
wget http://dl.fullcirclemagazine.org/issue104_en.pdf
wget http://dl.fullcirclemagazine.org/issue103_en.pdf
wget http://dl.fullcirclemagazine.org/issue102_en.pdf
wget http://dl.fullcirclemagazine.org/issue101_en.pdf
wget http://dl.fullcirclemagazine.org/issue100_en.pdf
wget http://dl.fullcirclemagazine.org/issue99_en.pdf
wget http://dl.fullcirclemagazine.org/issue98_en.pdf
wget http://dl.fullcirclemagazine.org/issue97_en.pdf
wget http://dl.fullcirclemagazine.org/issue96_en.pdf
wget http://dl.fullcirclemagazine.org/issue95_en.pdf
wget http://dl.fullcirclemagazine.org/issue94_en.pdf
wget http://dl.fullcirclemagazine.org/issue93_en.pdf
wget http://dl.fullcirclemagazine.org/issue92_en.pdf
wget http://dl.fullcirclemagazine.org/issue91_en.pdf
wget http://dl.fullcirclemagazine.org/issue90_en.pdf
wget http://dl.fullcirclemagazine.org/issue89_en.pdf
wget http://dl.fullcirclemagazine.org/issue88_en.pdf
wget http://dl.fullcirclemagazine.org/issue87_en.pdf
wget http://dl.fullcirclemagazine.org/issue86_en.pdf
wget http://dl.fullcirclemagazine.org/issue85_en.pdf
wget http://dl.fullcirclemagazine.org/issue84_en.pdf
wget http://dl.fullcirclemagazine.org/issue83_en.pdf
wget http://dl.fullcirclemagazine.org/issue82_en.pdf
wget http://dl.fullcirclemagazine.org/issue81_en.pdf
wget http://dl.fullcirclemagazine.org/issue80_en.pdf
wget http://dl.fullcirclemagazine.org/issue79_en.pdf
wget http://dl.fullcirclemagazine.org/issue78_en.pdf
wget http://dl.fullcirclemagazine.org/issue77_en.pdf
wget http://dl.fullcirclemagazine.org/issue76_en.pdf
wget http://dl.fullcirclemagazine.org/issue75_en.pdf
wget http://dl.fullcirclemagazine.org/issue74_en.pdf
wget http://dl.fullcirclemagazine.org/issue73_en.pdf
wget http://dl.fullcirclemagazine.org/issue72_en.pdf
wget http://dl.fullcirclemagazine.org/issue71_en.pdf
wget http://dl.fullcirclemagazine.org/issue70_en.pdf
wget http://dl.fullcirclemagazine.org/issue69_en.pdf
wget http://dl.fullcirclemagazine.org/issue68_en.pdf
wget http://dl.fullcirclemagazine.org/issue67_en.pdf
wget http://dl.fullcirclemagazine.org/issue66_en.pdf
wget http://dl.fullcirclemagazine.org/issue65_en.pdf
wget http://dl.fullcirclemagazine.org/issue64_en.pdf
wget http://dl.fullcirclemagazine.org/issue63_en.pdf
wget http://dl.fullcirclemagazine.org/issue62_en.pdf
wget http://dl.fullcirclemagazine.org/issue61_en.pdf
wget http://dl.fullcirclemagazine.org/issue60_en.pdf
wget http://dl.fullcirclemagazine.org/issue59_en.pdf
wget http://dl.fullcirclemagazine.org/issue58_en.pdf
wget http://dl.fullcirclemagazine.org/issue57_en.pdf
wget http://dl.fullcirclemagazine.org/issue56_en.pdf
wget http://dl.fullcirclemagazine.org/issue55_en.pdf
wget http://dl.fullcirclemagazine.org/issue54_en.pdf
wget http://dl.fullcirclemagazine.org/issue53_en.pdf
wget http://dl.fullcirclemagazine.org/issue52_en.pdf
wget http://dl.fullcirclemagazine.org/issue51_en.pdf
wget http://dl.fullcirclemagazine.org/issue50_en.pdf
wget http://dl.fullcirclemagazine.org/issue49_en.pdf
wget http://dl.fullcirclemagazine.org/issue48_en.pdf
wget http://dl.fullcirclemagazine.org/issue47_en.pdf
wget http://dl.fullcirclemagazine.org/issue46_en.pdf
wget http://dl.fullcirclemagazine.org/issue45_en.pdf
wget http://dl.fullcirclemagazine.org/issue44_en.pdf
wget http://dl.fullcirclemagazine.org/issue43_en.pdf
wget http://dl.fullcirclemagazine.org/issue42_en.pdf
wget http://dl.fullcirclemagazine.org/issue41_en.pdf
wget http://dl.fullcirclemagazine.org/issue40_en.pdf
wget http://dl.fullcirclemagazine.org/issue39_en.pdf
wget http://dl.fullcirclemagazine.org/issue38_en.pdf
wget http://dl.fullcirclemagazine.org/issue37_en.pdf
wget http://dl.fullcirclemagazine.org/issue36_en.pdf
wget http://dl.fullcirclemagazine.org/issue35_en.pdf
wget http://dl.fullcirclemagazine.org/issue34_en.pdf
wget http://dl.fullcirclemagazine.org/issue33_en.pdf
wget http://dl.fullcirclemagazine.org/issue32_en.pdf
wget http://dl.fullcirclemagazine.org/issue31_en.pdf
wget http://dl.fullcirclemagazine.org/issue30_en.pdf
wget http://dl.fullcirclemagazine.org/issue29_en.pdf
wget http://dl.fullcirclemagazine.org/issue28_en.pdf
wget http://dl.fullcirclemagazine.org/issue27_en.pdf
wget http://dl.fullcirclemagazine.org/issue26_en.pdf
wget http://dl.fullcirclemagazine.org/issue25_en.pdf
wget http://dl.fullcirclemagazine.org/issue24_en.pdf
wget http://dl.fullcirclemagazine.org/issue23_en.pdf
wget http://dl.fullcirclemagazine.org/issue22_en.pdf
wget http://dl.fullcirclemagazine.org/issue21_en.pdf
wget http://dl.fullcirclemagazine.org/issue20_en.pdf
wget http://dl.fullcirclemagazine.org/issue19_en.pdf
wget http://dl.fullcirclemagazine.org/issue18_en.pdf
wget http://dl.fullcirclemagazine.org/issue17_en.pdf
wget http://dl.fullcirclemagazine.org/issue16_en.pdf
wget http://dl.fullcirclemagazine.org/issue15_en.pdf
wget http://dl.fullcirclemagazine.org/issue14_en.pdf
wget http://dl.fullcirclemagazine.org/issue13_en.pdf
wget http://dl.fullcirclemagazine.org/issue12_en.pdf
wget http://dl.fullcirclemagazine.org/issue11_en.pdf
wget http://dl.fullcirclemagazine.org/issue10_en.pdf
wget http://dl.fullcirclemagazine.org/issue9_en.pdf
wget http://dl.fullcirclemagazine.org/issue8_en.pdf
wget http://dl.fullcirclemagazine.org/issue7_en.pdf
wget http://dl.fullcirclemagazine.org/issue6_en.pdf
wget http://dl.fullcirclemagazine.org/issue5_en.pdf
wget http://dl.fullcirclemagazine.org/issue4_en.pdf
wget http://dl.fullcirclemagazine.org/issue3_en.pdf
wget http://dl.fullcirclemagazine.org/issue2_en.pdf
wget http://dl.fullcirclemagazine.org/issue1_en.pdf
